import { VERSION } from "./version.js";

// Todo lo que el wizard decide o genera. Funciones puras a partir de aquí:
// los secretos se generan fuera (en init) para que esto sea testeable.
export interface SetupConfig {
  chatProvider: "anthropic" | "openai" | "ollama";
  embeddingProvider: "openai" | "ollama";
  anthropicApiKey?: string;
  openaiApiKey?: string;
  openaiBaseUrl?: string;
  /** Solo para Ollama: modelo de chat elegido (el server ya trae default). */
  chatModel?: string;
  adminToken: string;
  postgresPassword: string;
  port: number;
  allowedOrigins: string[];
}

// Debe coincidir EXACTAMENTE con el modelo de embeddings (ver .env.example).
// El wizard no pregunta: usa los modelos por defecto de cada adaptador
// (text-embedding-3-small → 1536, nomic-embed-text → 768).
export function embeddingDimensions(provider: SetupConfig["embeddingProvider"]): number {
  return provider === "ollama" ? 768 : 1536;
}

const quote = (value: string) => (/[\s#"']/.test(value) ? JSON.stringify(value) : value);

export function buildEnvFile(config: SetupConfig): string {
  const lines: string[] = [
    "# Docsera configuration — generated by `npx docsera`.",
    "# Full reference of every variable:",
    "# https://github.com/mikeljc-dev/docsera/blob/main/.env.example",
    "",
    `LLM_PROVIDER=${config.chatProvider}`,
  ];

  if (config.chatModel) {
    lines.push(`LLM_MODEL=${quote(config.chatModel)}`);
  }

  lines.push(
    "",
    `EMBEDDING_PROVIDER=${config.embeddingProvider}`,
    "# Must match the embedding model; re-ingest everything if you change it.",
    `EMBEDDING_DIMENSIONS=${embeddingDimensions(config.embeddingProvider)}`,
    "",
  );

  if (config.anthropicApiKey) {
    lines.push(`ANTHROPIC_API_KEY=${quote(config.anthropicApiKey)}`);
  }
  if (config.openaiApiKey) {
    lines.push(`OPENAI_API_KEY=${quote(config.openaiApiKey)}`);
  }
  if (config.openaiBaseUrl) {
    lines.push("# OpenAI-compatible API endpoint (Gemini, Groq, Mistral, LM Studio...).");
    lines.push(`OPENAI_BASE_URL=${quote(config.openaiBaseUrl)}`);
  }

  lines.push(
    "",
    "# Password of the bundled Postgres container (docker-compose.yml reads it too).",
    `POSTGRES_PASSWORD=${config.postgresPassword}`,
    "",
    "# Port where Docsera listens on this machine.",
    `PORT=${config.port}`,
    "",
    "# Origins allowed to embed the widget (CORS), comma-separated.",
    `ALLOWED_ORIGINS=${config.allowedOrigins.join(",")}`,
    "",
    "# Protects POST /ingest and the dashboard. Keep it secret.",
    `ADMIN_TOKEN=${config.adminToken}`,
    "",
  );

  return lines.join("\n");
}

export function buildComposeFile(): string {
  // ${POSTGRES_PASSWORD} y ${PORT} los interpola Docker Compose desde el .env
  // del mismo directorio; no son placeholders a rellenar.
  return `# Docsera — generated by \`npx docsera\`.
# \`docker compose up -d\` starts everything: Postgres (with pgvector) and the
# Docsera server (API + widget + dashboard in a single service).

services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: docsera
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: docsera
    # Not exposed to the host on purpose: only the server needs to reach it.
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docsera"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    # DOCSERA_IMAGE is only meant for developing Docsera itself (points to a
    # locally built image); as a user you never need to set it.
    image: \${DOCSERA_IMAGE:-ghcr.io/mikeljc-dev/docsera:${VERSION}}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Inside the Docker network the db has its own hostname, and the server
      # always listens on 3000 — the host port mapping below is what changes.
      DATABASE_URL: postgresql://docsera:\${POSTGRES_PASSWORD}@db:5432/docsera
      PORT: 3000
      # Ollama runs on the host, not in this compose; this URL reaches it from
      # inside the container.
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    extra_hosts:
      # host.docker.internal only exists by default on Docker Desktop
      # (Mac/Windows); this makes it work on Linux too.
      - "host.docker.internal:host-gateway"
    ports:
      - "\${PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
`;
}

export function buildWidgetSnippet(serverUrl: string): string {
  return `<script src="${serverUrl}/widget.js" data-server="${serverUrl}"></script>`;
}
